### ISSUE TITLE
Yönlendirmedeki hataların düzenlenmesi gerekiyor.

### ISSUE THREAD

**Issue by Akileus77** [SelimPolat16/twitch-clone-vue#1]
Yönlendirmedeki hataların düzeltilmesi konusunda uğraşıyorum.

**Comment by selimpolat16** [comment]
Yönlendirmedeki hataları düzenlendiğiniz için teşekkür ederiz .

**Comment by selimpolat16** [comment]
Yönlendirmedeki hataları düzenlediğiniz için teşekkür ederiz.
